### ISSUE TITLE
Add JMX Exporter Configs for Producers within the Confluent Server

### ISSUE THREAD

**Issue by nerdynick** [confluentinc/jmx-monitoring-stacks#62]
When Control Center is enabled we leverage the ConfluentMetricsReporter within the Brokers. We should capture these metrics into prometheus. 

Example Configs:

```
- pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):\w* 
   name: kafka_producer_$2 
   labels: 
     client-id: "$1"
- pattern: kafka.producer<type=producer-node-metrics, client-id=(.+), node-id=(.+)><>(.+):\w* 
   name: kafka_producer_$3 
   labels: 
     client-id: "$1" 
     broker: "$2"
- pattern: kafka.producer<type=producer-topic-metrics, client-id=(.+), topic=(.+)><>(.+):\w* 
   name: kafka_producer_$3 
   labels: 
     client-id: "$1" 
     topic: "$2"
```
