### ISSUE TITLE
Don't have ksql Queries status show in ksql-cluster dashboard

### ISSUE THREAD

**Issue by thititongumpun** [confluentinc/jmx-monitoring-stacks#86]
ksql_ksql_metrics_ksql_queries_query_status

![image](https://user-images.githubusercontent.com/55313215/184829174-fb2524f1-1f31-4af7-86a2-30176846c636.png)

![image](https://user-images.githubusercontent.com/55313215/184828992-f69df450-8ef2-43cd-8dac-01119c890666.png)

**Comment by jeqo** [comment]
Hi there! Will need a bit more info. Are you using [this JMX](https://github.com/confluentinc/jmx-monitoring-stacks/blob/7.2-post/shared-assets/jmx-exporter/confluent_ksql.yml) exporter config for ksql?

**Comment by thititongumpun** [comment]
Thank jeqo its solve by i remove confluent.ksql.yml ksql_metrics .* .+ to accepted blank ksql.cluster.id

**Comment by mariusstaicu** [comment]
cannot make it work, can you give some more details @thititongumpun on what you did to make it work ?

**Comment by mariusstaicu** [comment]
seems like it is not working when following the installation instructions in readme

**Comment by thititongumpun** [comment]
@mariusstaicu sure, If your connect-cluster have no cluster name like connect-cluster by default just do  replace in confluent.ksql.yml for prometheus config in  **ksql_metrics .*** to  **ksql_metrics .+**

**Comment by okouyad** [comment]
@thititongumpun i am having this  issue today. I try to read your answer  many  time, but i  don't get  it. 
Can you share a bit of config so we can see how it looks like. 

Otherwise @jeqo i am having the same issue. I am using the  latest jmx config for ksql db. everything works expect for that queries status panel. Can you confirm that the current ksql jmx config in the repo actually work ?

**Comment by okouyad** [comment]
when i list my bean using jolokia is shows as such

`status=_confluent-ksql-query_CST_ELSEVIER_CBE_RESNET_ORGANISM_93,type=ksql-queries`

**Comment by okouyad** [comment]
so it is the reverse of the current pattern. I try  to change it to 
```

        - labels:
            $3: $4
            ksql_query: $1
          name: ksql_ksql_metrics_$2_$3
          pattern: 'io.confluent.ksql.metrics<status=_confluent-ksql-query_(.+), type=(.+)><>(.+): (.+)'
          value: "1"
          valueFactor: 1
```
but  no sucsess
